### ISSUE TITLE
3D physics heightfield

### ISSUE THREAD

**Issue by josephrocca** [turbulenz/turbulenz_engine#48]
Any plans on implementing a heightfield for the low level 3d physics?

Cheers

**Comment by deltaluca** [comment]
No plans as it stands, but should be able to do it atleast by creating a triangle mesh for the heightmap surface. The 3d physics benchmark sample has a procedurally created traingle mesh geometry (the bowl) to see how that might be done.

**Comment by josephrocca** [comment]
Ah, great, thanks!
